# fly.toml app configuration file generated for voyalog-be on 2024-09-16T14:30:41+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "CHANGE_ME"
primary_region = "ams"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
